### ISSUE TITLE
Typo in time zone confirmation logic (ANS variable)

### ISSUE THREAD

**Issue by wickeddoc87** [straytripod/LibreNMS-Install#5]
Hi, 

There is a typo in the script’s time zone confirmation logic, specifically in the section where the user’s input for the time zone setting is checked.

In this part of the code, the variable ASN is used instead of ANS, which results in an incorrect condition check. Additionally, there is a single quotation mark (') within NO', which needs to be corrected.

Affected Code:

`if [ "$ANS" = "N" ] || [ "$ANS" = "No" ] || [ "$ASN" = "NO'" ]...........`

Suggested Fix:

Replace ASN with ANS and remove the extra quotation mark in NO'. The correct condition should look like this:

`if [ "$ANS" = "N" ] || [ "$ANS" = "No" ] || [ "$ANS" = "NO" ]............`

**Comment by straytripod** [comment]
This has been fixed. 
Thank you

**Comment by wickeddoc87** [comment]
There is stil the extra quotation mark which should be removed  "NO'" -->  "NO"

**Comment by straytripod** [comment]
Fixed. I didn't see it. Thanks
